# Generated by Django 5.2 on 2026-05-28 16:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateField()),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISCHARGED', 'Discharged')], default='ACTIVE', max_length=12)),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('discharge_type', models.CharField(blank=True, choices=[('RECOVERED', 'Recovered'), ('TRANSFERRED', 'Transferred'), ('AGAINST_ADVICE', 'Against Medical Advice'), ('ABSCONDED', 'Absconded'), ('EXPIRED', 'Expired')], max_length=15)),
                ('discharge_notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('VACANT', 'Vacant'), ('OCCUPIED', 'Occupied')], default='VACANT', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('diagnosis', models.TextField()),
                ('guardian_name', models.CharField(blank=True, max_length=255)),
                ('guardian_phone', models.CharField(blank=True, max_length=20)),
                ('admitting_doctor', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VitalsThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vital_type', models.CharField(choices=[('BP_SYSTOLIC', 'BP Systolic'), ('BP_DIASTOLIC', 'BP Diastolic'), ('PULSE', 'Pulse'), ('TEMPERATURE', 'Temperature'), ('SPO2', 'SpO₂'), ('WEIGHT', 'Weight')], max_length=15, unique=True)),
                ('below_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('above_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('FINANCE', 'Finance'), ('NURSE', 'Nurse')], default='NURSE', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='AdditionalCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('DRUGS', 'Drugs'), ('SNACKS', 'Snacks'), ('PERSONAL_CARE', 'Personal Care'), ('SPECIALIST', 'Specialist'), ('OTHER', 'Other')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charge_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_charges', to=settings.AUTH_USER_MODEL)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='additional_charges', to='api.admission')),
            ],
        ),
        migrations.AddField(
            model_name='admission',
            name='bed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='api.bed'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_period_start', models.DateField()),
                ('billing_period_end', models.DateField()),
                ('base_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], default='UNPAID', max_length=10)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='api.admission')),
            ],
            options={
                'unique_together': {('admission', 'billing_period_start', 'billing_period_end')},
            },
        ),
        migrations.AddField(
            model_name='admission',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='api.patient'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_on', models.DateField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='api.invoice')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='api.room'),
        ),
        migrations.CreateModel(
            name='VitalReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(choices=[('AM', 'Morning (AM)'), ('PM', 'Evening (PM)')], max_length=2)),
                ('recorded_at', models.DateTimeField()),
                ('bp_systolic', models.PositiveSmallIntegerField()),
                ('bp_diastolic', models.PositiveSmallIntegerField()),
                ('pulse', models.PositiveSmallIntegerField()),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=4)),
                ('spo2', models.PositiveSmallIntegerField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('has_flag', models.BooleanField(default=False)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_readings', to='api.admission')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_vitals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('room', 'label')},
        ),
    ]
