# Generated by Django 5.2 on 2026-08-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_patient_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('BEHAVIOUR', 'Behaviour'), ('ILLNESS', 'Illness'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='patients', to='api.tag'),
        ),
    ]
