# Generated by Django 5.2 on 2026-08-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_tag_patient_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='admission',
            name='opening_balance_as_of',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_opening_balance',
            field=models.BooleanField(default=False),
        ),
    ]
