# Generated by Django 5.2 on 2026-08-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_admission_opening_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='place',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
