# Generated by Django 5.2 on 2026-08-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_backfill_payment_receipts'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_settlement',
            field=models.BooleanField(default=False),
        ),
    ]
