# Generated by Django 5.2 on 2026-08-18 08:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_invoice_is_settlement'),
    ]

    operations = [
        # Preserve the old age data as a deprecated column (rollback reference,
        # dropped next release) rather than dropping it. Reads now use the
        # computed `age` property from date_of_birth.
        migrations.RenameField(
            model_name='patient',
            old_name='age',
            new_name='legacy_age',
        ),
        migrations.AddField(
            model_name='patient',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Aadhar number must be 12 digits.')]),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_of_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='food_preference',
            field=models.CharField(blank=True, choices=[('VEG', 'Vegetarian'), ('NON_VEG', 'Non-vegetarian')], max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_alive',
            field=models.BooleanField(default=True),
        ),
    ]
