# Generated by Django 5.2 on 2026-08-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_patient_age_patient_aadhar_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='aadhar_scan',
            field=models.FileField(blank=True, null=True, upload_to='aadhar_scans/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='patient_photos/'),
        ),
    ]
