# Generated by Django 5.2 on 2026-08-19 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_user_role_followup_inquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(choices=[('NURSE', 'Nurse'), ('ATTENDANT', 'Attendant'), ('COOK', 'Cook'), ('CLEANER', 'Cleaner'), ('SECURITY', 'Security'), ('ADMIN_STAFF', 'Administrative'), ('OTHER', 'Other')], default='OTHER', max_length=12)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
                'ordering': ['name'],
            },
        ),
    ]
