# Generated by Django 5.2 on 2026-08-19 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_from', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_food_rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_from', '-id'],
            },
        ),
    ]
