# Generated by Django 5.2 on 2026-08-24 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _remap_stages(apps, schema_editor):
    """Map the old inquiry statuses onto the new pipeline stages and seed the
    owner from the creator."""
    Inquiry = apps.get_model('api', 'Inquiry')
    mapping = {'FOLLOWED_UP': 'CONTACTED', 'CONVERTED': 'ADMITTED', 'CLOSED': 'LOST'}
    for old, new in mapping.items():
        Inquiry.objects.filter(status=old).update(status=new)
    # Default the owner to whoever created the lead.
    Inquiry.objects.filter(assigned_to__isnull=True, created_by__isnull=False).update(
        assigned_to=models.F('created_by')
    )


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_staff_gender_staffmealrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='lost_reason',
            field=models.CharField(blank=True, choices=[('COST', 'Cost'), ('DISTANCE', 'Distance'), ('CHOSE_OTHER', 'Chose another provider'), ('NOT_READY', 'Not ready / declined'), ('UNREACHABLE', 'Unreachable'), ('OTHER', 'Other')], max_length=12),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='lost_reason_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='source',
            field=models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('PHONE', 'Phone'), ('WALKIN', 'Walk-in'), ('WEB', 'Web'), ('REFERRAL', 'Referral'), ('OP_CONSULT', 'OP consult'), ('OP_IMPORT', 'OP list import')], max_length=12),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('CONSULTED', 'Consulted'), ('ADMITTED', 'Admitted'), ('LOST', 'Lost')], default='NEW', max_length=12),
        ),
        migrations.RunPython(_remap_stages, _noop),
    ]
