# Generated by Django 5.2 on 2026-08-24 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_inquiry_assigned_to_inquiry_lost_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('NOTE', 'Note'), ('CALL', 'Call'), ('WHATSAPP', 'WhatsApp'), ('STAGE_CHANGE', 'Stage change'), ('FOLLOW_UP', 'Follow-up'), ('SYSTEM', 'System')], max_length=12)),
                ('body', models.TextField(blank=True)),
                ('outcome', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.inquiry')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.patient')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['inquiry', '-created_at'], name='api_activit_inquiry_941071_idx'), models.Index(fields=['patient', '-created_at'], name='api_activit_patient_170b22_idx')],
            },
        ),
    ]
