# Generated by Django 5.2 on 2026-08-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='contact_consent',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('GRANTED', 'Granted'), ('DECLINED', 'Declined')], default='UNKNOWN', max_length=10),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='do_not_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact_consent',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('GRANTED', 'Granted'), ('DECLINED', 'Declined')], default='UNKNOWN', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='do_not_contact',
            field=models.BooleanField(default=False),
        ),
    ]
