# Generated by Django 5.2 on 2026-08-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_inquiry_contact_consent_inquiry_do_not_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='consulted_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
