# Generated by Django 5.2 on 2026-08-25 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_inquiry_consulted_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='api.inquiry'),
        ),
        migrations.AddField(
            model_name='followup',
            name='kind',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AFTERCARE', 'Aftercare'), ('OP_NUDGE', 'OP nudge')], default='MANUAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='followup',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='api.patient'),
        ),
    ]
