# Generated by Django 5.2 on 2026-09-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_invoice_waived_amount_waiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='alternate_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
