# Generated by Django 5.2 on 2026-09-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='max_inpatient_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
