# Generated by Django 5.2 on 2026-09-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_systemsetting_max_inpatient_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='source',
            field=models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('PHONE', 'Phone'), ('WALKIN', 'Walk-in'), ('WEB', 'Web'), ('REFERRAL', 'Referral'), ('OP_CONSULT', 'OP consult'), ('OP_IMPORT', 'OP list import'), ('READMISSION', 'Re-admission')], max_length=12),
        ),
    ]
