# Generated by Django 5.2 on 2026-09-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_inquiry_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('GALLERY', 'Gallery carousel'), ('LOGO', 'Site logo'), ('FOCUS', 'Care-area image')], max_length=16)),
                ('image', models.ImageField(upload_to='site_images/')),
                ('title_en', models.CharField(blank=True, max_length=120)),
                ('title_ta', models.CharField(blank=True, max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['section', 'sort_order', 'id'],
            },
        ),
    ]
