# Generated by Django 5.2 on 2026-09-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_siteimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='pickup_requested',
            field=models.BooleanField(default=False),
        ),
    ]
