# Generated by Django 5.2 on 2026-09-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_inquiry_pickup_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='completed_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
