# Generated by Django 5.2 on 2026-09-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_followup_completed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='planned_discharge_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
